## Numpy 기초

In [1]:
import numpy

### 1차원 배열

In [2]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [5]:
type(array1)

numpy.ndarray

In [6]:
array1.shape

(11,)

### 2차원 배열

In [9]:
array2 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [10]:
type(array2)

numpy.ndarray

In [11]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
array2.shape

(3, 4)

In [13]:
array1.size

11

In [14]:
array2.size

12

shape은 행렬의 크기, size는 행렬의 요소의 개수를 담음

### numpy array를 만드는 다양한 방법

In [15]:
array3 = numpy.full(6, 7) # 균일한 값으로 생성
array4 = numpy.zeros(6, dtype=int) # 영행렬 생성
array5 = numpy.ones(6, dtype=int) # 모든 값이 1인 행렬
array6 = numpy.random.random(6) # 랜덤한 값들로 생성
array7 = numpy.arange(6) # 연속된 값으로 생성
array8 = numpy.arange(1, 5) # 두 값 사이의 연속된 값으로 생성
array9 = numpy.arange(3, 17, 3) # 두 값 사이의 s만큼의 간격으로 생성

In [17]:
print(array3)
print(array4)
print(array5)
print(array6)
print(array7)
print(array8)
print(array9)

[7 7 7 7 7 7]
[0 0 0 0 0 0]
[1 1 1 1 1 1]
[0.7822591  0.66880819 0.30457424 0.77317481 0.1985938  0.75663732]
[0 1 2 3 4 5]
[1 2 3 4]
[ 3  6  9 12 15]


### 신주쿠 흥부부대찌개

일본에는 한식 열풍이 불고 있습니다. 기회를 엿본 영훈이는 대기업을 퇴사하고 신주쿠에 프랜차이즈 ‘흥부부대찌개’ 가맹점을 냈습니다.

그러나 보수적인 아버지께서는 번듯한 직장을 박차고 나온 영훈이가 못마땅합니다. 아버지를 안심시켜 드리기 위해 매달 매출을 보고하려고 하는데요. 엔화(¥)로 저장한 매출 데이터를 원화(₩)로 변환하는 작업이 필요합니다.

마침 numpy를 배운 우리가 도와줄 수 있겠네요. 엔화 매출이 담겨 있는 파이썬 리스트가 주어졌습니다. 1엔에 10.08원이라고 가정하고, 원화 매출이 담긴 numpy array를 만들어 출력해 주세요.

반복문은 사용하면 안 됩니다!

주의: 자동 채점 과제입니다. 정답 출력 코드는 **print**가 없는 방식으로 작성해 주세요. (예시: won_array)



In [18]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

yen_array = np.array(revenue_in_yen)
won_array = yen_array * 10.08

In [19]:
won_array

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

### 흥부부대찌개 LA 진출

흥부부대찌개 신주쿠점의 흥행에 성공한 영훈이는 여세를 몰아 LA에도 가맹점을 하나 냈습니다.

이제 아버지께 매출을 보고하기 위한 프로세스가 조금 복잡해졌습니다. 각 지점의 매출을 원화로 변환시키고 더해야 하죠. 1엔에 10.08원, 1달러에 1138원이라고 가정하세요. 그리고 두 지점의 매출의 합이 원화로 담긴 numpy array를 만들어 출력해주세요.

반복문은 사용하면 안 됩니다!

주의: 자동 채점 과제입니다. 정답 출력 코드는 **print**가 없는 방식으로 작성해 주세요. (예시: won_array)

In [20]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

# 코드를 작성하세요.
yen_array = np.array(revenue_in_yen)
dollar_array = np.array(revenue_in_dollar)
won_array = yen_array * 10.08 + dollar_array * 1138

In [21]:
won_array

array([4389600., 5248000., 4818800., 5108200., 6825000., 3004400.,
       3521400., 5817000., 5033400., 4630200., 5439800., 6220200.,
       4900000., 4370000., 4253000., 5524400., 6421800., 6145400.,
       5651200., 3560400., 3612400., 5150400., 6220200., 7016800.,
       5589400., 6623400., 3560400., 3814000., 6018600., 5046400.,
       4568400.])

### Boolean 연산

In [22]:
booleans = np.array([True, True, False, True, True])

In [23]:
np.where(booleans)

(array([0, 1, 3, 4], dtype=int64),)

In [24]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [25]:
np.where(array1 > 4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [26]:
filter = np.where(array1 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [27]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

### 흥부부대찌개 목표 일 매출

영훈이가 창업한 흥부부대찌개 신주쿠점은 이제 직장인들에게 소문난 맛집입니다. 그러나 매일같이 성공적인 것은 아닙니다. 목표 일 매출을 달성하지 못하는 날들이 아직 꽤 있거든요. 영훈이가 생각하는 성공적인 하루 매출은 20만 엔입니다.

성공적이지 않은 날의 매출만 골라서 보고 싶습니다. 20만 엔 이하의 매출만 담긴 numpy array를 출력해주세요.
반복문은 사용하면 안 됩니다!

주의: 자동 채점 과제입니다. 정답 출력 코드는 print 없이 작성해 주세요. (예시: bad_days_revenue)

In [28]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 코드를 작성하세요.
yen = np.array(revenue_in_yen)
bad_days_revenue = np.where(yen < 200000)

In [29]:
# 정답 출력
yen[bad_days_revenue]

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

### Numpy 기본 통계

In [30]:
print(array1)

print(array1.max()) # 최댓값
print(array1.min()) # 최솟값
print(array1.mean()) # 평균값
print(np.median(array1)) # 중앙값
print(array1.std()) # 표준편차
print(array1.var()) # 분산

[ 2  3  5  7 11 13 17 19 23 29 31]
31
2
14.545454545454545
13.0
9.680004098079865
93.70247933884298
